name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -t go-wasm .
    - name: Publish
      run: |
        git config --global user.email ""
        git config --global user.name "GitHub Pages Deploy"
        git checkout --orphan gh-pages
        git rm -rf .
        out=$(mktemp -d)
        docker cp $(docker create --rm go-wasm):/usr/share/nginx/html "$out"
        find "$out/html" -mindepth 1 -maxdepth 1 -exec cp -r {} ./ \;  # Glob doesn't always pick up hidden files by default
        git add .
        git commit -am "Deploy to GitHub Pages"
        git push --force origin gh-pages
