name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Publish
      run: |
        out="$(mktemp -d)/out"
        mv ./out "$out"
        git config --global user.email ""
        git config --global user.name "GitHub Pages Deploy"
        git checkout --orphan gh-pages
        git rm -rf .
        mv "$out"/* ./
        echo hackpad.org > CNAME
        git add .
        git commit -am "Deploy to GitHub Pages"
        git push --force origin gh-pages
